- id: onos
  type: group
  role: [onos]
  requires: [deploy_start]
  required_for: [deploy_end, primary-controller, controller]
  tasks: [hiera, setup_repositories, fuel_pkgs, globals, tools, logging, onos_install]
  parameters:
    strategy:
      type: parallel
- id: onos_install
  type: puppet
  version: 2.0.0
  groups: [onos]
  requires: [deploy_start, hosts, firewall, globals]
  required_for: [deploy_end, openstack-network-start]
  parameters:
    puppet_manifest: puppet/manifests/onos-install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720
- id: onos_service
  type: puppet
  version: 2.0.0
  role: [onos]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/onos-service.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1400
- id: onos_ha
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  requires: [onos_service]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/onos-ha.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1400
- id: onos_config_ovs_controller
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  requires: [onos_ha]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/ovs-controller.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
- id: onos_config_ovs_compute
  type: puppet
  version: 2.0.0
  role: [compute]
  cross-depends:
     - name: onos_ha
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: puppet/manifests/ovs-compute.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
- id: onos_config_neutron
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  requires: [onos_config_ovs_controller,onos_config_ovs_compute]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/neutron-config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800
- id: onos_create_neutron_db
  type: puppet
  version: 2.0.0
  role: [primary-controller]
  requires: [onos_config_neutron]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/neutron-db.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800
- id: onos_start_neutron
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  requires: [onos_create_neutron_db]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/neutron-start.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800
- id: onos_config_net
  type: puppet
  version: 2.0.0
  role: [onos]
  requires: [onos_start_neutron]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/netconfig.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
