- id: onos
  type: group
  role: [onos]
  requires: [deploy_start]
  required_for: [deploy_end, primary-controller, controller]
  tasks: [hiera, setup_repositories, fuel_pkgs, globals, tools, logging, onos_install, netconfig]
  parameters:
    strategy:
      type: parallel
- id: ovs_update
  type: puppet
  version: 2.0.0
  groups: [primary-controller,controller,compute]
  requires: [deploy_start]
  required_for: [netconfig, deploy_end]
  condition: "settings:onos.enable_sfc == true"
  parameters:
    puppet_manifest: puppet/manifests/ovs-update.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720
- id: onos_install
  type: puppet
  version: 2.0.0
  groups: [onos]
  requires: [deploy_start, hosts, firewall, globals]
  required_for: [deploy_end, openstack-network-start]
  parameters:
    puppet_manifest: puppet/manifests/onos-install.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 720
- id: onos_service
  type: puppet
  version: 2.0.0
  role: [onos]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/onos-service.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1400
- id: onos_ha
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  cross-depends:
     - name: onos_service
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/onos-ha.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1400
- id: onos_config_ovs_controller
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  requires: [onos_ha]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/ovs-controller.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
- id: onos_config_ovs_compute
  type: puppet
  version: 2.0.0
  role: [compute]
  cross-depends:
     - name: onos_ha
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    puppet_manifest: puppet/manifests/ovs-compute.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 600
- id: onos_config_neutron
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  cross-depends:
     - name: onos_config_ovs_compute
  requires: [onos_config_ovs_controller]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/neutron-config.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800
- id: onos_start_neutron
  type: puppet
  version: 2.0.0
  role: [primary-controller,controller]
  requires: [onos_config_neutron]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: puppet/manifests/neutron-start.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 1800
    timeout: 600
- id: onos_dashboard_registration
  type: puppet
  role: [primary-controller]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/onos-dashboard.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 180
- id: onos_sfcvm_upload
  type: puppet
  role: [primary-controller]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/onos-uploadvm.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 180
