#!/bin/bash
set -eux
DIR="$(dirname `readlink -f $0`)"
TARGET="${DIR}/deployment_scripts/puppet/modules/onos/files"
#base_url=http://205.177.226.237:9999/onosfw
base_url=http://192.168.212.92:9999
repo_target="${DIR}/repositories/ubuntu"
onos=onos-1.6.0.tar.gz
package=package_ovs_debian.tar.gz
jdk=jdk-8u51-linux-x64.tar.gz
repo=repository.tar
img=firewall_block_image.img

cd $TARGET
if [ ! -f $onos ]; then
  wget  $base_url/$onos -P $TARGET
fi

if [ ! -f $jdk ]; then
  wget  $base_url/$jdk -P $TARGET
  wget  $base_url/$repo -P $TARGET
  wget  $base_url/$img -P $TARGET
fi

cd $repo_target
rm -rf *.deb
if [ ! -f $package ]; then
  wget  $base_url/$package -P $repo_target
fi

tar zxf $repo_target/$package  -C $repo_target 
rm -rf $repo_target/$package

